# Generated by Django 6.0.7 on 2026-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('quotation_no', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('business_gst', models.CharField(blank=True, max_length=100)),
                ('business_website', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_gst', models.CharField(blank=True, max_length=100)),
                ('client_address', models.TextField(blank=True)),
            ],
        ),
    ]
