# Generated by Django 6.0.7 on 2026-08-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_balance_amount_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_holder',
            field=models.CharField(blank=True, default='KENSTACK TECHNOLOGIES PRIVATE LIMITED', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, default='1602010000000351', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='Karur Vysya Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.CharField(blank=True, default='Trichy Gundur Branch', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ifsc',
            field=models.CharField(blank=True, default='KVBL0001602', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='note_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='account_holder',
            field=models.CharField(blank=True, default='KENSTACK TECHNOLOGIES PRIVATE LIMITED', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='account_number',
            field=models.CharField(blank=True, default='1602010000000351', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='bank_name',
            field=models.CharField(blank=True, default='Karur Vysya Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='branch',
            field=models.CharField(blank=True, default='Trichy Gundur Branch', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ifsc',
            field=models.CharField(blank=True, default='KVBL0001602', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='note_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='business_name',
            field=models.CharField(default='KENSTACK TECHNOLOGIES PRIVATE LIMITED', max_length=255),
        ),
    ]
