# Generated by Django 6.0.7 on 2026-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_invoice_business_address_invoice_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project_type',
            field=models.CharField(blank=True, default='Website', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(blank=True, default='Website', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_gst',
            field=models.CharField(blank=True, default='33AAMCK6128J1ZB', max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='business_gst',
            field=models.CharField(blank=True, default='33AAMCK6128J1ZB', max_length=100),
        ),
    ]
