# Generated by Django 6.0.7 on 2026-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enable_gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='enable_gst',
            field=models.BooleanField(default=True),
        ),
    ]
